[package]
name = "instruction-macros"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
instruction-macros-derive = { path = "../instruction-macros-derive" }
instruction-macros-traits = { path = "../instruction-macros-traits" }
