[package]
name = "instruction-macros-impl"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
itertools.workspace = true
quote.workspace = true
proc-macro2.workspace = true
strum.workspace = true
strum_macros.workspace = true
syn.workspace = true
